blank_issues_enabled: true
contact_links:
  - name: 检查友链添加状态
    url: https://www.setbun.com/links/
    about: 查看您的友链是否添加
  - name: 加入友链博主TG群
    url: https://t.me/setbungroup
    about: 如果你添加了友链，欢迎加入本群，我们共同《無限進步》！
