name: 添加友链
description: 请先阅读自述文件后按照issues模板填写即可添加
title: "「新增」："
labels: ["友链添加"]
assignees: ["FrederickBun"]
body:
  - type: checkboxes
    id: pre-check
    attributes:
      label: 交换友链检查清单
      description: 请确保确认后，再提交 Issue
      options:
        - label: "已经阅读 `README.md`"
        - label: "您的站点类型为 `博客`"
        - label: "[网站域名符合规定](https://github.com/FrederickAsYou/friends/tree/main?tab=readme-ov-file#%E4%BA%A4%E6%8D%A2%E5%89%8D%E8%AF%B7%E9%98%85%E8%AF%BB)"
        - label: "网站内容符合国家规定"
  - type: textarea
    id: name
    attributes:
      label: 友链信息
      description: 请在双引号中填写，不要修改格式。
      value: |
        ```yaml
        {
            title: ''
            description: ''
            link: ''
            avatar: ''
        }
        ```
  - type: textarea
    id: friends-link
    attributes:
      label: "站点友链地址"
      placeholder: "请填写在何处可以看到您所添加的友链"
